const courses = [
  {
    id: 1,
    title: "JavaScript Eğitimi",
    instructor:"Abdullah DEMİRKOL",
    level:"Giriş Seviyesi",
    price: 1750,
    img: "https://www.freecodecamp.org/news/content/images/2021/06/javascriptfull.png",
    quantity: 1,
  },
  {
    id: 2,
    title: "MongoDb Eğitimi",
    instructor:"Ayşenur DEMİRKOL",
    level:"Orta Seviyesi",
    price: 254,
    img: "https://user-images.githubusercontent.com/40702606/118755471-cf58b300-b860-11eb-979a-16d263b320a8.png",
    quantity: 13,
  },
  {
    id: 3,
    title: "React Eğitimi",
    instructor:"Abdullah DEMİRKOL",
    level:"İleri Seviyesi",
    price: 3254,
    img: "https://process.fs.teachablecdn.com/ADNupMnWyR7kCWRvm76Laz/resize=width:705/https://www.filepicker.io/api/file/fGWjtyQtG4JE7UXgaPAN",
    quantity: 2,
  },
  {
    id: 4,
    title: "NodeJS & ExpressJS Eğitimi",
    instructor:"Asya Hilal DEMİRKOL",
    level:"Giriş Seviyesi",
    price: 3211,
    img: "https://www.freecodecamp.org/news/content/images/2021/04/nodeexpress.png",
    quantity: 1,
  },
  {
    id: 5,
    title: "Angular Eğitimi",
    instructor:"Abdullah DEMİRKOL",
    level:"Orta Seviyesi",
    price: 1350,
    img: "https://www.sipexe.com/assets/courses/Angular.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "Tailwind CSS Eğitimi",
    instructor:"Asya Hilal DEMİRKOL",
    level:"Giriş Seviyesi",
    price: 955,
    img: "https://i.ytimg.com/vi/UBOj6rqRUME/maxresdefault.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Redux Eğitimi",
    instructor:"Abdullah DEMİRKOL",
    level:"İleri Seviyesi",
    price: 1250,
    img: "https://www.courses.tutorialswebsite.com/assets/front/img/category/react-redux-category.jpeg",
    quantity: 1,
  },
];
export default courses;
